#!/bin/sh
#
# PROVIDE: xen-watchdog
# REQUIRE: DAEMON
#
# description: Run domain watchdog daemon
#

. /etc/rc.subr

name="xenwatchdog"

load_rc_config $name

LD_LIBRARY_PATH="${libdir}"
export LD_LIBRARY_PATH

command="${sbindir}/xenwatchdogd"
start_cmd="echo Starting ${name}. && PATH=${PATH}:${sbindir} ${command} 30 15"

run_rc_command "$1"
